### ISSUE TITLE
Feature Request: Allow setting word break

### ISSUE THREAD

**Issue by timokoessler** [usewaypoint/email-builder-js#120]
It would be nice if it were possible to set the css [word-break](https://developer.mozilla.org/en-US/docs/Web/CSS/word-break#syntax) property, e.g. to force wrapping of long inline URLs.

**Comment by jordanisip** [comment]
Hi @timokoessler, appreciate the suggestion. Just as a heads up, we've held off on this since `word-break` [isn't properly supported across email clients](https://www.caniemail.com/search/?s=word-break). 

In many cases, `word-break` applies `break-all` which is much less ideal since it breaks in the middle of a word. Example:

![CleanShot 2024-08-10 at 09 57 05@2x](https://github.com/user-attachments/assets/b341a684-d227-4879-b554-097ed80e8e44)

So at the moment, this is not something we will fix since lean toward wide client support that degrades well. However, in the future we hope to add the ability to set custom CSS rules from the editor so folks can override if it makes sense for their audience.
