### ISSUE TITLE
More global fonts, RTL support

### ISSUE THREAD

**Issue by HadiAlMarzooq** [usewaypoint/email-builder-js#73]
Hello there, I really like the way you guys are doing this and thank you for sharing it to the public.

However, as an Arabic developer, I find it a hustle to download the desired font (Arabic supported fonts) or to modify the template manually each time I export to HTML. What I would love to is to have the following:

1- Add more global fonts, try google fonts maybe? 
2- RTL Support, its an HTML attribute.
3- Add the ability to use variables using the format `{{variableName}}`.

Again I appreciate the work and efforts.
Thanks guys.

**Comment by jordanisip** [comment]
Hi @HadiAlMarzooq, great feedback and questions, thanks for sharing.

> Add more global fonts, try google fonts maybe?

At the moment, we plan on keeping the list short since custom fonts are [not widely supported on emails.](https://www.caniemail.com/features/css-at-font-face/). We did, however, add the font selector to the global styles panel in #72.
 
<img width="397" alt="CleanShot 2024-04-12 at 09 36 46@2x" src="https://github.com/usewaypoint/email-builder-js/assets/5899/7026100e-f13a-46c0-8788-6839c8b264d5">

> RTL Support, its an HTML attribute.

This is something we'd like to support. We'll add it to our list, thanks!

> Add the ability to use variables using the format {{variableName}}.

Good idea, but we are choosing to keep this builder lightweight and to reserve variables for our [Pro builder on Waypoint](https://www.usewaypoint.com/docs/template-test-data).
